---
title: "Hindi: Data Processing"
output: html_document
---
## Packages
```{r}
library(tidyverse)
library(mgsub)
library(ggplot2)


# Create tables
library(gt)
library(webshot)
library(xtable)

```

## Read in Data
```{r}

if (!dir.exists("data/raw")) {
  dir.create("data/raw")
  print("Input directory created. Please place data file into ./data/raw.")
  
} else {
  if (!file.exists("data/raw/HindiAcceptabilityDemo210727.txt")) {
    print("Data not found. Please place data file into ./data/raw.")
    
  } else {
    hindi_read <- read_delim("data/raw/HindiAcceptabilityDemo210727.txt", "\t") 
  }
}

# Remove additional empty rows from some sort of manual value
hindi_read <- hindi_read %>%  select(1:22)

# Take a look at data
glimpse(hindi_read)
head(hindi_read)

# View(hindi_read)
length(unique(hindi_read$participant))
```

```{r}
# Keep copy of questions
hindi_q <- slice(hindi_read, 1)
```

```{r}
# Check some stuff
# colnames(hindi_read)
# length(unique(hindi$condition))
```

## Clean Data
```{r}
# Rename question columns
hindi <- hindi_read %>% rename_at(vars(7:22), ~ c("loc_child", "loc_now", "hear_child", "speak_child", "hear_now", "speak_now", "read_now", "write_now", "comfort_understand", "comfort_read", "comfort_write", "comfort_speak", "HUregion_time", "HUregion_from", "native_HU", "native_Eng")) %>%

  # Fix strange single column errors
  mutate(HUregion_time = case_when(participant == "R_8ABOSyqKc2VugbD" ~ "4/12",
                                   TRUE ~ HUregion_time)) %>%
  mutate(loc_child = case_when(participant == "R_3qrql5FeZWfCLet" ~ "Texas, USA",
                               TRUE ~ loc_child)) %>%  
  # filter(participant == "R_3JEnBflQnuMjBrB") %>% # one row is just missing all ques. data
  filter(loc_child !="Country") %>%
  
  # Remove all NA participants
  filter(!is.na(loc_child))
  # drop_na() %>%
  # relocate(native_HU, native_Eng, .before=hear_child)

# Check number of subjects
length(unique(hindi$participant))
```

```{r}
# Check summary
hindi %>% mutate_if(is.character, as.factor) %>% summary()
```

### Full Dataframe
```{r}
# Clean responses & code categorical groups
hindi <- hindi %>% 
  
  mutate_if(is.character, tolower) %>%
  
  # Replace numeric NAs with 0 (assume no response = 0 percent/comfort)
  mutate(across(hear_child:comfort_speak, ~ coalesce(.x, 0))) %>%
  
  # Create native status categories
  mutate(native_group = case_when(native_HU == "yes" & native_Eng == "yes" ~ "both",
                                  native_HU == "yes" & native_Eng == "no" ~ "HU",
                                  native_HU == "no" & native_Eng == "yes" ~ "Eng",
                                  native_HU == "no" & native_Eng == "no" ~ "neither")) %>%
  
  # Clean free response text
  mutate(country_child = mgsub(loc_child, c("(", ")"), c(",", ""), fixed=TRUE)) %>%
  mutate(country_child = mgsub(country_child, c("(.*,)", "united arab emirates", "us$|vermont and hawaii."), c("", "uae", "usa"))) %>%
  mutate(country_child = str_trim(country_child)) %>%
  
  mutate(country_now = mgsub(loc_now, c("(", ")", "."), c(",", "", ""), fixed=TRUE)) %>%
  mutate(country_now = mgsub(country_now, c("(.*,)|(.*-)", "united states of america|united states$|us$|both chicago and new york|texas$|texas usa", "united kingdom"), c("", "usa", "uk"))) %>%
  mutate(country_now = str_trim(country_now)) %>%
  
  # Create residential history categories
  mutate(residence_group = case_when((country_child == "usa" | country_child == "canada") & 
                                       (country_now == "usa"| country_now == "canada") ~ "NorthAm",
                                     (country_child == "india" | country_child == "pakistan") & 
                                       (country_now == "india"| country_now == "pakistan") ~ "SouthAs",
                                     (country_child == "india" | country_child == "pakistan") & 
                                       (country_now == "usa"| country_now == "canada") ~ "SAtoNA",
                                     TRUE ~ "uncategorized"))
```


### By-Subject Dataframe

Check Questionnaire Responses
```{r}
# Only by-subject questionnaire responses
hindi_subj <- hindi %>% select(participant, loc_child:last_col()) %>%
  distinct()
# View(hindi_subj)

hindi_subj %>% count(native_group)
hindi_subj %>% count(residence_group)

```

```{r}
# Check NAs
# filter(hindi_subj, is.na(loc_child))
```


### Group Labels Dataframe
```{r}
# NOTE: Ignoring HUregion_time & HUregion_from columns right now

hindi_groups <- hindi %>% select(participant, native_group, residence_group) %>% distinct()
hindi_groups
```

## Descriptive Summary & Plots
```{r}
hindi_variable_means <- 
  hindi_subj %>% pivot_longer(hear_child:comfort_speak, names_to="variable", values_to="score") %>%
  mutate(variable = factor(variable, levels = c("hear_child", "speak_child", "hear_now", "speak_now", "read_now", "write_now", "comfort_understand", "comfort_speak", "comfort_read", "comfort_write"))) %>%
  group_by(variable) %>%
  summarize(n=n(),
            across(score, c(min = min, max = max, mean = mean, sd = sd), .names = "{.fn}")) #{.col}_{.fn}"
hindi_variable_means

```

```{r}
hindi_variable_means %>%
  ggplot(aes(x=variable, y=mean, fill=variable, color=variable)) +
  geom_col(position="dodge", width=0.8) +
  labs(x="Native Groups", y="Mean Rating Score", fill="Variable", color="Variable") +
  scale_alpha_discrete(guide = "none") +
  gg_theme() +
  scale_fill_brewer(palette = "Paired") + 
  scale_color_brewer(palette = "Paired") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  theme(legend.position = "bottom", legend.key.size = unit(.5, "cm"), legend.text = element_text(size=15))
```

```{r}
hindi_subj %>% pivot_longer(hear_child:comfort_speak, names_to="variable", values_to="score") %>%
  mutate(variable = factor(variable, levels = c("hear_child", "speak_child", "hear_now", "speak_now", "read_now", "write_now", "comfort_understand", "comfort_speak", "comfort_read", "comfort_write"))) %>%
  ggplot(aes(x=variable, y=score, fill=variable, color=variable)) + #
  geom_violin(width=1, alpha=0.1) +
  geom_jitter(width=0.05, alpha=0.2) +
  labs(x="Native Groups", y="Mean Rating Score", fill="Variable", color="Variable") +
  scale_alpha_discrete(guide = "none") +
  gg_theme() +
  scale_fill_brewer(palette = "Paired") + 
  scale_color_brewer(palette = "Paired") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  theme(legend.position = "bottom", legend.key.size = unit(.5, "cm"), legend.text = element_text(size=15))
```

```{r}
hindi_subj_mean <- 
  hindi_subj %>% group_by(native_group) %>%
  summarize(n=n(),
            across(hear_child:comfort_speak, mean))

# print(xtable(hindi_subj_mean, type = "latex"), file = "nativegroups.tex")
```

```{r}

hindi_subj %>% group_by(native_group) %>%
  summarize(across(hear_child:comfort_speak, mean)) %>%
  
  pivot_longer(hear_child:last_col(), names_to="variable", values_to="score") %>%
  mutate(variable = factor(variable, levels = c("hear_child", "speak_child", "hear_now", "speak_now", "read_now", "write_now", "comfort_understand", "comfort_speak", "comfort_read", "comfort_write"))) %>%

  ggplot(aes(x=variable, y=score, fill=variable, color=variable)) +
  geom_col(position="dodge", width=0.8) +
  facet_wrap(~native_group, ncol=4) +
  labs(x="Native Groups", y="Mean Rating Score", fill="Variable", color="Variable") +
  scale_alpha_discrete(guide = "none") +
  gg_theme() +
  scale_fill_brewer(palette = "Paired") + 
  scale_color_brewer(palette = "Paired") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  theme(legend.position = "bottom", legend.key.size = unit(.5, "cm"), legend.text = element_text(size=15))
```

```{r}
hindi_subj_mean <- 
  hindi_subj %>% group_by(residence_group) %>%
  summarize(across(hear_child:comfort_speak, mean))

# print(xtable(hindi_subj_mean, type = "latex"), file = "residencegroups.tex")
```

```{r}

hindi_subj %>% group_by(residence_group) %>%
  summarize(across(hear_child:comfort_speak, mean)) %>%
  
  pivot_longer(hear_child:last_col(), names_to="variable", values_to="score") %>%
  mutate(variable = factor(variable, levels = c("hear_child", "speak_child", "hear_now", "speak_now", "read_now", "write_now", "comfort_understand", "comfort_speak", "comfort_read", "comfort_write"))) %>%

  ggplot(aes(x=variable, y=score, fill=variable, color=variable)) +
  geom_col(position="dodge", width=0.8) +
  facet_wrap(~residence_group, ncol=4) +
  labs(x="Residence Group", y="Mean Rating Score", fill="Variable", color="Variable") +
  scale_alpha_discrete(guide = "none") +
  gg_theme() +
  scale_fill_brewer(palette = "Paired") + 
  scale_color_brewer(palette = "Paired") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  theme(legend.position = "bottom", legend.key.size = unit(.5, "cm"), legend.text = element_text(size=15))
```

## Save Processed Data
```{r}
if (!dir.exists("data/processed")) {
  dir.create("data/processed")
}

# save as Rdata
save(hindi, file="data/processed/hindi.RData")
save(hindi_subj, file="data/processed/hindi_subj.RData")
save(hindi_groups, file="data/processed/hindi_groups.RData")
```


# ...
# For Reference
```{r}
## From https://www.dezyre.com/recipes/check-multicollinearity-r

# hindi_langexp_var <- hindi_langexp %>% select(2:last_col())                         # independent variables 

# var <- cor(hindi_langexp_var)

# var_inv <- MASS::ginv(var)                                       # independent variables inverse correlation matrix 
# 
# colnames(var_inv) <- colnames(hindi_langexp_var)                      # rename the row names and column names
# rownames(var_inv) <- colnames(hindi_langexp_var)
# 
# corrplot::corrplot(var_inv,method='number',is.corr = F)              # visualize the multicollinearity

```
